require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: enable

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/mysql2-aws_rds_iam.rb

Metrics/MethodLength:
  Max: 15
  Exclude:
    - test/**/**.rb

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Exclude:
    - test/**/**.rb
